### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LReiz** [LReiz/ProGuitarHero#1]
- [x] Gravador de Microfone (ou da própria guitarra)
     - [x] Grava frames de 1024 samples
- [x] Processador de Notas
     - [x] Pega um conjunto de frames e transforma em uma frequência
     - [x] Transforma a frequência em um número que representanta a nota
     - [x] Distinguir silêncio de sons
- [x] Tocador de Música
     - [x] De acordo com a nota, toca o resto do riff/solo
